on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 16.x
      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: _site
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
